// LLM-backed /message endpoint for the moi-agent-dating skill's say-hi demo.
//
// Contract expected by say-hi.mjs:
//   POST /message
//   body:  { from: "<sender wallet hex>", text: "<greeting>" }
//   → 200  { ok: true, text: "<reply>" }
//
// The reply is generated by OpenAI's Chat Completions API. Each agent can have
// its own persona by setting AGENT_PERSONA. If OPENAI_API_KEY is missing this
// falls back to a dumb echo so the demo still runs offline.
//
// Run:    AGENT_NAME=Jill PORT=3941 node message-server.mjs
//
// Env:
//   PORT             listen port (default 3940)
//   AGENT_NAME       this agent's display name (default "an OpenClaw agent")
//   AGENT_PERSONA    full system prompt override (default is generated from AGENT_NAME)
//   OPENAI_API_KEY   if set, replies come from the LLM; otherwise echo fallback
//   OPENAI_MODEL     default "gpt-5.4-mini"
//   LLM_TIMEOUT_MS   default 25000 — abort if the LLM hangs

import http from 'node:http'

const PORT = Number(process.env.PORT ?? 3940)
const AGENT_NAME = process.env.AGENT_NAME ?? 'an OpenClaw agent'
const OPENAI_API_KEY = process.env.OPENAI_API_KEY
const OPENAI_MODEL = process.env.OPENAI_MODEL ?? 'gpt-5.4-mini'
const LLM_TIMEOUT_MS = Number(process.env.LLM_TIMEOUT_MS ?? 25000)

const DEFAULT_PERSONA =
  `You are ${AGENT_NAME}, an autonomous AI agent registered on the MOI on-chain agent ` +
  `registry. Another agent has reached out to you via your /message HTTP endpoint. ` +
  `Reply naturally in 1–2 short sentences. Stay in character as ${AGENT_NAME}. ` +
  `Do not pretend to be a different agent. Keep it friendly and direct.`

const AGENT_PERSONA = process.env.AGENT_PERSONA ?? DEFAULT_PERSONA

async function askLLM(from, text) {
  if (!OPENAI_API_KEY) {
    return `hi back — got "${text.slice(0, 80)}" from ${from.slice(0, 14)}… ` +
      `(OPENAI_API_KEY unset on this server — falling back to echo)`
  }

  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), LLM_TIMEOUT_MS)

  try {
    const res = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      signal: controller.signal,
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${OPENAI_API_KEY}`,
      },
      body: JSON.stringify({
        model: OPENAI_MODEL,
        messages: [
          { role: 'system', content: AGENT_PERSONA },
          {
            role: 'user',
            content:
              `Another MOI agent (wallet ${from.slice(0, 14)}…) just messaged you. ` +
              `Their message: "${text}"\n\nReply now in 1–2 short sentences as ${AGENT_NAME}.`,
          },
        ],
        max_completion_tokens: 200,
      }),
    })

    if (!res.ok) {
      const body = await res.text().catch(() => '<no body>')
      console.error(`[message-server] OpenAI HTTP ${res.status}: ${body.slice(0, 200)}`)
      return `(${AGENT_NAME} can't respond right now — OpenAI returned HTTP ${res.status})`
    }

    const json = await res.json()
    const reply = json?.choices?.[0]?.message?.content?.trim()
    if (!reply) {
      console.error(`[message-server] OpenAI returned empty content: ${JSON.stringify(json).slice(0, 300)}`)
      return `(${AGENT_NAME} can't respond right now — empty LLM output)`
    }
    return reply
  } catch (err) {
    if (err?.name === 'AbortError') {
      console.error(`[message-server] OpenAI call timed out after ${LLM_TIMEOUT_MS}ms`)
      return `(${AGENT_NAME} timed out talking to the LLM after ${LLM_TIMEOUT_MS}ms)`
    }
    console.error(`[message-server] OpenAI call failed: ${err?.message ?? err}`)
    return `(${AGENT_NAME} couldn't reach the LLM — ${err?.message ?? err})`
  } finally {
    clearTimeout(timer)
  }
}

const server = http.createServer(async (req, res) => {
  const send = (status, body) => {
    res.statusCode = status
    res.setHeader('Content-Type', 'application/json')
    res.end(JSON.stringify(body))
  }

  if (req.method === 'GET' && (req.url === '/' || req.url === '/health')) {
    return send(200, {
      ok: true,
      agent: AGENT_NAME,
      llm: OPENAI_API_KEY ? OPENAI_MODEL : 'echo-fallback',
      skills: ['say-hi'],
    })
  }

  if (req.method !== 'POST' || req.url !== '/message') {
    return send(404, { error: `unsupported route ${req.method} ${req.url}` })
  }

  let raw = ''
  for await (const chunk of req) raw += chunk

  let body
  try {
    body = JSON.parse(raw)
  } catch {
    return send(400, { error: 'body must be JSON' })
  }

  const from = typeof body?.from === 'string' ? body.from : '<unknown>'
  const text = typeof body?.text === 'string' ? body.text : ''
  const ts = new Date().toISOString()
  console.log(`[${AGENT_NAME}] ${ts}  IN  from=${from.slice(0, 14)}…  text=${JSON.stringify(text)}`)

  const reply = await askLLM(from, text)

  console.log(`[${AGENT_NAME}] ${new Date().toISOString()}  OUT  text=${JSON.stringify(reply.slice(0, 160))}`)

  return send(200, { ok: true, text: reply })
})

server.listen(PORT, '::', () => {
  console.log(`[${AGENT_NAME}] listening on http://localhost:${PORT} (dual-stack ::)`)
  console.log(`[${AGENT_NAME}] llm: ${OPENAI_API_KEY ? OPENAI_MODEL : 'OFF (echo fallback)'}`)
  console.log(`[${AGENT_NAME}] persona: ${AGENT_PERSONA.slice(0, 100)}${AGENT_PERSONA.length > 100 ? '…' : ''}`)
  console.log(`[${AGENT_NAME}] register an agent with: AGENT_URL=http://localhost:${PORT}`)
  console.log(`[${AGENT_NAME}] Ctrl+C to stop`)
})
